Task JDP240901-2: Skeleton for the GroupController
piotr-grosicki/project-jdp-2409-01 pull request #2
Opened 2024-09-01 10:53 UTC by martkow

Task JDP240901-2: Added a skeleton for the GroupController along with Swagger documentation.

2024-09-01 14:16 UTC, piotr-grosicki requested changes

2024-09-01 14:16 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/EcommerceeApplication.java
> +@OpenAPIDefinition(info = @Info(title = "JDP24-09-01 API"))
umowiliscie sie na uzywanie tego? wszyscy beda pisac dokumentacje?

2024-09-01 17:30 UTC, martkow commented on src/main/java/com/kodilla/ecommercee/EcommerceeApplication.java
> +@OpenAPIDefinition(info = @Info(title = "JDP24-09-01 API"))
O ile dobrze pamiętam, to tak. Jakby co to ja mogę spróbować podgarnąć dokumentację - usprawni ona Nam potem testowanie.

2024-09-01 19:39 UTC, martkow commented on src/main/java/com/kodilla/ecommercee/EcommerceeApplication.java
> +@OpenAPIDefinition(info = @Info(title = "JDP24-09-01 API"))
Tak, potwierdzone z grupą. Dokumentujemy usługi w Swagger.

2024-09-02 05:58 UTC, piotr-grosicki requested changes
konflikty https://www.jetbrains.com/help/idea/resolve-conflicts.html

2024-09-02 19:33 UTC, merged