JDP240901-4 OrderController & OrderDto small changes
piotr-grosicki/project-jdp-2409-01 pull request #24
Opened 2024-09-07 10:05 UTC by cdroma

2024-09-07 14:02 UTC, BogdanBrandys approved these changes

2024-09-07 14:03 UTC, BogdanBrandys commented
wszystko ok

2024-09-07 14:04 UTC, BogdanBrandys approved these changes
konflikty

2024-09-07 14:05 UTC, BogdanBrandys requested changes
konflikty

2024-09-08 08:40 UTC, cdroma commented
juz posprzatalem :)

2024-09-08 09:07 UTC, BogdanBrandys approved these changes
jest ok :)

2024-09-08 09:07 UTC, merged