Added README file
piotr-grosicki/project-jdp-2409-01 pull request #44
Opened 2024-09-13 12:17 UTC by BogdanBrandys

w sekcji dotyczącej endpointów, każdy który robi update oznaczyłem jako wymagający autoryzacji.

2024-09-13 19:17 UTC, martkow requested changes

2024-09-13 19:17 UTC, martkow commented on README.md
> +- PUT /v1/groups/{groupID} - Update group details (authenticated users) by ID.
groupID -> groupId

2024-09-13 19:17 UTC, martkow commented on README.md
> +**Cart:**
Cart -> Carts


Żeby zachować spójność z opisem w Swagger?

2024-09-13 19:17 UTC, martkow commented on README.md
> +- GET /v1/carts/{cartID}/items – Get current cart contents by ID.
cartID -> cartId

2024-09-13 19:17 UTC, martkow commented on README.md
> +- POST /v1/carts/{cartID}/items - Add item to the cart by ID.
cartID -> cartId

2024-09-13 19:17 UTC, martkow commented on README.md
> +- DELETE /v1/carts/{cartID}/items/{productID} – Remove item by product ID from the cart by cart ID.
cartID -> cartId

2024-09-13 19:17 UTC, martkow commented on README.md
> +- POST /v1/carts/{cartID}/orders - Create order from cart by ID.
cartID -> cartId

2024-09-13 19:17 UTC, martkow commented on README.md
> +**Order:**
Order -> Orders

2024-09-13 19:17 UTC, martkow commented on README.md
> +- GET /v1/orders/{orderID} – Get order by ID.
orderID -> orderId

2024-09-13 19:17 UTC, martkow commented on README.md
> +- PUT /v1/orders/{orderID} - Update order details (authenticated users) by ID.
orderID -> orderId

2024-09-13 19:17 UTC, martkow commented on README.md
> +- DELETE /v1/orders/{orderID} - Delete order by ID.
orderID -> orderId

2024-09-13 19:17 UTC, martkow commented on README.md
> +**User:**
User -> Users

2024-09-13 19:17 UTC, martkow commented on README.md
> +- PATCH /v1/users/{userID}/status – Update user status (authenticated users) by ID.
userID -> userId

2024-09-13 19:17 UTC, martkow commented on README.md
> +- PATCH /v1/users/{userID}/status – Update user status (authenticated users) by ID.
Możesz proszę rozważyć, czy jakoś lepiej nie brzmi forma:
Update user status by ID (authenticated users).


Przenieść w pozostałych również to doprecyzowanie w nawiasie na koniec zdania, wtedy jest rozdzielone, że np. aktualizacja statusu po ID użytkownika a dodatkowo endpoint jest dedykowany dla uwierzytelnionych użytkowników.

2024-09-13 19:17 UTC, martkow commented on README.md
> +- POST /v1/users/key - Create one hour token for user.
one-hour token

2024-09-13 19:17 UTC, martkow commented on README.md
> +- POST /v1/users/key - Create one hour token for user.
Generate a one-hour token for the user.

2024-09-13 19:17 UTC, martkow commented on README.md
> +  ./gradle test
Ponownie pytanie gradle czy gradlew.

2024-09-14 12:04 UTC, BogdanBrandys commented on README.md
> +- A tool like **Postman** to test the API endpoints
tutaj zostawiłbym jak jest. dałem tylko konkrety do instalacji

2024-09-14 12:16 UTC, BogdanBrandys commented on README.md
> +##Contributors
będzie alfabetycznie nazwiskami :)

2024-09-14 17:39 UTC, martkow approved these changes

2024-09-14 17:45 UTC, merged