JDP240901-49 Added KeyFilter
piotr-grosicki/project-jdp-2409-01 pull request #46
Opened 2024-09-13 15:49 UTC by BogdanBrandys

2024-09-13 21:42 UTC, martkow approved these changes

2024-09-13 22:04 UTC, martkow requested changes

2024-09-13 22:04 UTC, martkow commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    @PutMapping(value = "/modify/{orderId}", consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
W jakim celu to dodatkowe '/modify' w ścieżce? 
Nie będzie to spójne z pozostałymi zaprojektowanymi endpointami, np. z zaprojektowanym aktualizowaniem produktu '/v1/products/{productId}'.

Wcześniej '/v1/orders/{orderId}' odnosiło się do wersja 1 apki, dalej zasób orders, a dalej do konkretnego zasobu o identyfikatorze orderId, na którym wykonujemy PUT.

2024-09-14 12:22 UTC, BogdanBrandys commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    @PutMapping(value = "/modify/{orderId}", consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
wszystkie końcówki które coś modyfikują zmieniłem w ten sposób. Powód jest taki, że jak mapuje endpointy w filtrze to nie wskazuje tam rodzaju endpointu (POST, DELETE) 
Przykładowo dla Products mamy: 
- PUT /v1/products/{productId}
- DELETE /v1/products/{productId}
więc jak oznacze /v1/products/* do weryfikacji filtrem to zablokuje mi zarówno modyfikacje PUT ale również usuwanie DELETE

2024-09-14 17:51 UTC, martkow approved these changes

2024-09-14 17:53 UTC, merged