Task JDP240901-4: OrderController (with test endpoints) & OrderDto
piotr-grosicki/project-jdp-2409-01 pull request #5
Opened 2024-09-02 12:00 UTC by cdroma

2024-09-02 19:34 UTC, piotr-grosicki submitted a review, later dismissed

2024-09-02 19:34 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    @GetMapping
brakuje dokumentacji na ktora podobno sie zgodziliscie :)

2024-09-04 16:58 UTC, BogdanBrandys requested changes

2024-09-04 16:58 UTC, BogdanBrandys commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    @GetMapping
Roman wprowadził @Tag i @ Operation tak jak się umawialiśmy.

2024-09-04 16:58 UTC, BogdanBrandys commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
>  public class OrderDto {
OrderDto mamy już w mainie. Klasę stworzyła Marta

2024-09-06 09:47 UTC, closed without merging